### ISSUE TITLE
TypeError in building a query

### ISSUE THREAD

**Issue by Michael-E-Rose** [sosia-dev/sosia#26]
Working on Dorfman, Albert (7102085360) for year 1982 yields the following error:

```
Traceback (most recent call last):
  File "<input>", line 15, in <module>
  File "<input>", line 17, in perform_group_search
  File "<input>", line 33, in perform_individual_search
  File "C:\Users\rosm\AppData\Roaming\Python\Python38\site-packages\sosia\classes\original.py", line 366, in inform_matches
    matches = inform_matches(self, fields, stop_words, verbose, refresh,
  File "C:\Users\rosm\AppData\Roaming\Python\Python38\site-packages\sosia\processing\extracting.py", line 221, in inform_matches
    p = Scientist([auth_id], self.year, period=self.period,
  File "C:\Users\rosm\AppData\Roaming\Python\Python38\site-packages\sosia\classes\scientist.py", line 304, in __init__
    res = base_query("docs", q, refresh, fields=integrity_fields)
  File "C:\Users\rosm\AppData\Roaming\Python\Python38\site-packages\sosia\processing\utils.py", line 84, in try_query
    Query: {args[0]['query']}"
TypeError: string indices must be integers
```

**Comment by Michael-E-Rose** [comment]
Fixed in https://github.com/sosia-dev/sosia/commit/21d85fc738573d4c1ba5c6f7fc850a2ba9ea1ef8
