### ISSUE TITLE
sqlite3.OperationalError: disk I/O error

### ISSUE THREAD

**Issue by Michael-E-Rose** [sosia-dev/sosia#31]
Strange error when initiating an instance:

```
from sosia import Orignal

au = Original(7201538867, treatment_year=2015)
```

results in

```
Traceback (most recent call last):
  File "C:\Users\rosm\AppData\Local\Programs\Python\Python38\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-12-59a3b9befab2>", line 1, in <module>
    au = Original(author, treatment_year=year)
  File "C:\Users\rosm\AppData\Local\Programs\Python\Python38\lib\site-packages\sosia\classes\original.py", line 183, in __init__
    Scientist.__init__(self, self.identifier, treatment_year, refresh=refresh,
  File "C:\Users\rosm\AppData\Local\Programs\Python\Python38\lib\site-packages\sosia\classes\scientist.py", line 349, in __init__
    df = get_authors(self.identifier, self.sql_conn,
  File "C:\Users\rosm\AppData\Local\Programs\Python\Python38\lib\site-packages\sosia\processing\getting.py", line 35, in get_authors
    data, missing = retrieve_authors(authors, conn)
  File "C:\Users\rosm\AppData\Local\Programs\Python\Python38\lib\site-packages\sosia\processing\caching\retrieving.py", line 27, in retrieve_authors
    insert_temporary_table(df, merge_cols=cols, conn=conn)
  File "C:\Users\rosm\AppData\Local\Programs\Python\Python38\lib\site-packages\sosia\processing\caching\inserting.py", line 98, in insert_temporary_table
    cursor.execute("DROP TABLE IF EXISTS temp")
sqlite3.OperationalError: disk I/O error
```

**Comment by Michael-E-Rose** [comment]
Could not replicate, probably fixed long ago.
